stages:
  - deploy
  - destroy

variables:
  SAM_CLI_TELEMETRY: 0

before_script:
  - pip install aws-sam-cli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION

deploy:
  stage: deploy
  script:
    - |
      if [ "$DEPLOYMENT_TYPE" = "proxy" ]; then
        sam deploy --template-file proxy-template.yaml --stack-name huggin-proxy-stack --capabilities CAPABILITY_IAM --no-confirm-changeset --parameter-overrides InstanceCount=$PROXY_COUNT InstanceType=$PROXY_INSTANCE_TYPE
      elif [ "$DEPLOYMENT_TYPE" = "vpn" ]; then
        sam deploy --template-file vpn-template.yaml --stack-name huggin-vpn-stack --capabilities CAPABILITY_IAM --no-confirm-changeset --parameter-overrides InstanceCount=$VPN_COUNT InstanceType=$VPN_INSTANCE_TYPE
      fi
  only:
    variables:
      - $DEPLOYMENT_TYPE

destroy:
  stage: destroy
  script:
    - |
      if [ "$DEPLOYMENT_TYPE" = "proxy" ]; then
        aws cloudformation delete-stack --stack-name huggin-proxy-stack
      elif [ "$DEPLOYMENT_TYPE" = "vpn" ]; then
        aws cloudformation delete-stack --stack-name huggin-vpn-stack
      fi
  when: manual
  only:
    variables:
      - $ACTION == "destroy"